In [1]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt

from ta import add_all_ta_features 
from ta.momentum import *
from ta.trend import *

from ta_library import *

In [2]:
df = pd.read_csv("../data/EURUSD_M15.csv", sep="\t")
# df = df[-10000:]
df.reset_index(inplace=True)
df = df.rename(columns={'Open':'open', 'High':'high', 'Low':'low', 'Close':'close', 'Volume':'volume'})
df = df.drop(['index', 'Time'], axis=1)
df = df.dropna()

In [3]:
df

           open     high      low    close  volume
0       1.10788  1.10802  1.10770  1.10800     402
1       1.10799  1.10801  1.10779  1.10789     689
2       1.10789  1.10789  1.10720  1.10760     950
3       1.10759  1.10822  1.10727  1.10819    1169
4       1.10820  1.11146  1.10819  1.11003    2637
...         ...      ...      ...      ...     ...
199995  1.12280  1.12297  1.12258  1.12259    1870
199996  1.12258  1.12264  1.12243  1.12252    1564
199997  1.12253  1.12270  1.12252  1.12264    1059
199998  1.12263  1.12274  1.12253  1.12256     927
199999  1.12256  1.12294  1.12231  1.12235    2326

[200000 rows x 5 columns]

In [4]:
get_ema(df)
get_vwap(df)
get_stochasticrsi(df)
get_macd(df)
change(df)
get_trend(df)

,open,high,low,close,volume,ema_100,ema_200,ema_signal,vwap,vwap_signal,...,close_pct_change,open_change,open_pct_change,high_change,high_pct_change,low_change,low_pct_change,volume_change,volume_pct_change,trend
0,1.10788,1.10802,1.10770,1.10800,402,1.108000,1.108000,0,1.107907,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
1,1.10799,1.10801,1.10779,1.10789,689,1.107998,1.107999,0,1.107900,-1,...,-0.009928,0.00011,0.009929,-0.00001,-0.000903,0.00009,0.008125,287.0,71.393035,0
2,1.10789,1.10789,1.10720,1.10760,950,1.107990,1.107995,0,1.107743,-1,...,-0.026176,-0.00010,-0.009025,-0.00012,-0.010830,-0.00059,-0.053259,261.0,37.880987,0
3,1.10759,1.10822,1.10727,1.10819,1169,1.107994,1.107997,0,1.107783,1,...,0.053268,-0.00030,-0.027079,0.00033,0.029786,0.00007,0.006322,219.0,23.052632,0
4,1.10820,1.11146,1.10819,1.11003,2637,1.108034,1.108017,0,1.108936,1,...,0.166037,0.00061,0.055075,0.00324,0.292361,0.00092,0.083087,1468.0,125.577417,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
199995,1.12280,1.12297,1.12258,1.12259,1870,1.121991,1.118664,0,1.122903,-1,...,-0.017813,-0.00021,-0.018700,-0.00011,-0.009794,-0.00021,-0.018703,260.0,16.149068,0
199996,1.12258,1.12264,1.12243,1.12252,1564,1.122001,1.118702,0,1.122712,-1,...,-0.006236,-0.00022,-0.019594,-0.00033,-0.029386,-0.00015,-0.013362,-306.0,-16.363636,0
199997,1.12253,1.12270,1.12252,1.12264,1059,1.122014,1.118742,0,1.122628,1,...,0.010690,-0.00005,-0.004454,0.00006,0.005345,0.00009,0.008018,-505.0,-32.289003,0
199998,1.12263,1.12274,1.12253,1.12256,927,1.122025,1.118780,0,1.122578,-1,...,-0.007126,0.00010,0.008908,0.00004,0.003563,0.00001,0.000891,-132.0,-12.464589,0
199999,1.12256,1.12294,1.12231,1.12235,2326,1.122031,1.118815,0,1.122571,-1,...,-0.018707,-0.00007,-0.006235,0.00020,0.017814,-0.00022,-0.019599,1399.0,150.916936,0

In [5]:
df = df.dropna()

In [6]:
df = df.reindex(columns=['open', 'open_change', 'open_pct_change', 'high', 'high_change', 'high_pct_change', 'low', 'low_change', 'low_pct_change',
                        'close', 'close_change', 'close_pct_change', 'volume', 'volume_change', 'volume_pct_change', 
                        'ema_100', 'ema_200', 'ema_signal', 'vwap', 'vwap_signal', 'stochrsi', 'stochrsi_k', 'stochrsi_d', 'stochrsi_signal',
                        'macd',	'macd_s', 'macd_signal', 
                        'trend'
    ])

In [7]:

df = df.round(6)

In [8]:
df.dtypes

open                 float64
open_change          float64
open_pct_change      float64
high                 float64
high_change          float64
high_pct_change      float64
low                  float64
low_change           float64
low_pct_change       float64
close                float64
close_change         float64
close_pct_change     float64
volume                 int64
volume_change        float64
volume_pct_change    float64
ema_100              float64
ema_200              float64
ema_signal             int64
vwap                 float64
vwap_signal            int64
stochrsi             float64
stochrsi_k           float64
stochrsi_d           float64
stochrsi_signal        int64
macd                 float64
macd_s               float64
macd_signal            int64
trend                  int64
dtype: object

In [9]:
df.to_csv("final_df_minute-15_period-8_feature-27.csv")